channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.3
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.1.3
  - pandas==2.3.3
  - pathlib==1.0.1
  - psutil==7.0.0
  - pyarrow==20.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
